channels:
  - pytorch
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9.10
  - ipython=8.0.1
  - ipykernel=6.9.0
  - ipywidgets=7.6.5
  - numpy=1.22.2
  - pandas=1.4.0
  - matplotlib=3.3.2
  - tqdm=4.62.3
  - snakemake=6.15.5
  - tsfresh=0.19.0
  - sktime[all_extras]=0.10.0
  - pytorch=1.10.2
  - pytorch-lightning=1.5.9
  - xgboost=1.5.1
  - lightgbm=3.3.2
  - seaborn=0.11.2
  - tensorflow=2.4.1
  - keras=2.4.3
  - shap=0.40.0
  - pip:
      - esig==0.9.7
      - catch22==0.2.0
